# Viewpoint and image plane
geometry_msgs/Point viewpoint
geometry_msgs/Point top_left_corner
geometry_msgs/Point top_right_corner
geometry_msgs/Point bottom_left_corner
# Range
float32 min_distance
float32 max_distance
# Depth image dimensions
uint16 width
uint16 height
---
sensor_msgs/Image depth_image